### ISSUE TITLE
V1.1 (March 2nd update) – burying cards

### ISSUE THREAD

**Issue by jamiekoi** [Quip13/Anki-Zoom#1]
Issue:
When the add-on is installed and enabled, and you want to manually bury card (hotkey: minus), the screen freezes. If you continue to press minus key, you start burying more cards without even seeing them.

To re-produce:
Enable Anki Zoom v1.1
Start reviewing cards (make note of how many cards to be reviewed)
Press minus to bury card
Screen freezes
Press minus couple more times
Screen still frozen, and more cards being buried without being seen what they are

My setup:
Anki 2.1.20
MacOS Catalina (latest)
Happy to provide my add-ons list installed.

**Comment by AnKingMed** [comment]
I'm having the same issue when I try to use the rememorize add-on and I'm on the same setup

**Comment by Quip13** [comment]
Ah yeah should be fixed now
