### ISSUE TITLE
Feature request: keep zoom levels consistent per profile

### ISSUE THREAD

**Issue by okBryan** [Quip13/Anki-Zoom#4]
I have two profiles that I have to adjust the zoom each time I switch.

**Comment by ccz-2** [comment]
Unfortunately Anki doesn't make this easy - each addon can only have one config per install, independent of profiles.
It's possible to do this, but it would make the config prohibitively complex and difficult to maintain/edit.
This feature request should be on an application level; you could submit a request for profile-dependent config to Damien (the guy who runs Anki) if you want this to happen.
Sorry mate
