### ISSUE TITLE
Feature request : would it be possible to zoom at the browser or edit screen ? 

### ISSUE THREAD

**Issue by Sinerbek** [Quip13/Anki-Zoom#5]
would it be possible to zoom at the browser or edit screen ?

**Comment by ccz-2** [comment]
That feature is already in Anki - go to prefernces -> user interface size
Let me know if that works for you

**Comment by Sinerbek** [comment]
that is awesome , I didn't even notice that such feature was already there.
You save my eyes from a lot of strains thanks and have a good day.
