### ISSUE TITLE
Answer Not Displayed

### ISSUE THREAD

**Issue by ghost** [Quip13/Anki-Zoom#6]
Hello, 
I am having trouble with my close deletion cards and some basic cards as well not showing the answer as I am reviewing. I confirmed its an issue with this addon but disabling/enabling it. Please let me know what other information you might need.

**Comment by ccz-2** [comment]
Thanks for the bug report. How reproducible is this bug - does it happen consistently? Does zooming in/out update the page to display the answer?

**Comment by ghost** [comment]
I realized I did not have the most current version of Anki installed. I had 2.1 but just not updated. The problem seems to have resolved. Sorry for the trouble

**Comment by ccz-2** [comment]
No worries - glad it's working!
